name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz
        python -m pip install --upgrade pip
        pip install flake8 pytest pep8-naming
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --ignore "N801, E203, E266, E501, W503, F812, F401, F841, E741, N803, N802, N806" minitorch/ tests/
    
    - name: Run regular tests
      run: |
        echo "Module 0"
        pytest tests -x -m task0_1
        pytest tests -x -m task0_2
        pytest tests -x -m task0_3
        pytest tests -x -m task0_4
        echo "Module 1"
        pytest tests -x -m task1_1
        pytest tests -x -m task1_2
        pytest tests -x -m task1_3
        pytest tests -x -m task1_4
        echo "Module 2"
        pytest tests -x -m task2_1
        pytest tests -x -m task2_2
        pytest tests -x -m task2_3
        pytest tests -x -m task2_4
        echo "Module 3"
        pytest tests -x -m task3_1
        pytest tests -x -m task3_2
        echo "Module 4"
        pytest tests -x -m task4_1
        pytest tests -x -m task4_2
        pytest tests -x -m task4_3
        pytest tests -x -m task4_4
    
    - name: Check for GPU
      id: check-gpu
      run: |
        if command -v nvidia-smi &> /dev/null && nvidia-smi -L | grep -q "GPU"; then
          echo "GPU available"
          echo "gpu=true" >> $GITHUB_ENV
        else
          echo "No GPU detected"
          echo "gpu=false" >> $GITHUB_ENV
        fi
    
    - name: Run GPU-dependent tests
      if: env.gpu == 'true' || env.gpu == ''
      run: |
        echo "Running GPU-dependent tests..."
        pytest tests -x -m task3_3
        pytest tests -x -m task3_4
    
    - name: Skip GPU-dependent tests
      if: env.gpu != 'true' || env.gpu == ''
      run: |
        echo "Skipping GPU-dependent tests. No GPU available."

